version: 2
before:
  hooks:
    - go mod tidy
project_name: terraform-provider-tekton

builds:
  - id: tekton
    binary: terraform-provider-tekton
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags: "-s -w"
    env:
      - CGO_ENABLED=0

archives:
  - format: zip
    name_template: '{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}'
    # files:
    #   - LICENSE

# checksum:
#   name_template: 'checksums.txt'

release:
  disable: false
  github:
    owner: SamuelDBines
    name: terraform-provider-tekton

changelog:
  disable: true
