version: 2
before:
  hooks:
    - go mod tidy
project_name: terraform-provider-tekton

builds:
  - id: tekton
    binary: '{{ .ProjectName }}_v{{ .Version }}_x5'
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    ignore:
      - goarch: arm
        goos: windows
      - goarch: arm64
        goos: freebsd
      - goarch: arm64
        goos: windows
      - goarch: arm64
        goos: openbsd
    ldflags:
      - -s -w -X 'github.com/SamuelDBines/terraform-provider-tekton/version.ProviderVersion={{ .Version }}'
    env:
      - CGO_ENABLED=0

archives:
  - format: zip
    name_template: '{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}'
    # files:
    #   - LICENSE
checksum:
  algorithm: sha256
  extra_files:
    - glob: 'terraform-registry-manifest.json'
      name_template: '{{ .ProjectName }}_{{ .Version }}_manifest.json'
  name_template: '{{ .ProjectName }}_{{ .Version }}_SHA256SUMS'
# checksum:
#   name_template: 'checksums.txt'

release:
  disable: false
  github:
    owner: SamuelDBines
    name: terraform-provider-tekton
  extra_files:
    - glob: 'terraform-registry-manifest.json'
      name_template: '{{ .ProjectName }}_{{ .Version }}_manifest.json'

changelog:
  disable: true
